name: annualreport2020
baseurl:
host: 0.0.0.0
plugins: ['jekyll/minibundle']
title: >
  mySociety Year in Review 2020
description: >
  mySociety provides technology, research and data to help people be active citizens, in more than 40 countries around the world.
production_url: https://2020.mysociety.org
