name: annualreport2021
baseurl:
host: 0.0.0.0
plugins: ['jekyll/minibundle']
title: >
  mySociety Year in Review 2021
description: >
  mySociety provides technology, research and data to help people be active citizens, in more than 40 countries around the world.
production_url: https://2021.mysociety.org
