name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        year: [ '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Run Build
      run: |
        bundle exec sass --update assets/sass:assets/css --style compressed
        bundle exec jekyll build
      working-directory: ${{ matrix.year }}
